# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\vidtrim\ui\VideoTrimMainWindow_UI.ui'
#
# Created: Fri Dec 23 23:50:20 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VideoTrimMainWindow_UI(object):
    def setupUi(self, VideoTrimMainWindow_UI):
        VideoTrimMainWindow_UI.setObjectName("VideoTrimMainWindow_UI")
        VideoTrimMainWindow_UI.resize(839, 656)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/images/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VideoTrimMainWindow_UI.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(VideoTrimMainWindow_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.play_btn = QtGui.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(410, 40, 75, 23))
        self.play_btn.setObjectName("play_btn")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 40, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalSlider_2 = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(730, 40, 91, 19))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 40, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(550, 40, 81, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.video_widget = QtGui.QWidget(self.centralwidget)
        self.video_widget.setGeometry(QtCore.QRect(20, 150, 791, 461))
        self.video_widget.setObjectName("video_widget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 100, 811, 21))
        self.widget.setObjectName("widget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 130, 311, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(705, 80, 101, 20))
        self.label_4.setObjectName("label_4")
        VideoTrimMainWindow_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(VideoTrimMainWindow_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        VideoTrimMainWindow_UI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(VideoTrimMainWindow_UI)
        self.statusbar.setObjectName("statusbar")
        VideoTrimMainWindow_UI.setStatusBar(self.statusbar)
        self.actionSource_Files = QtGui.QAction(VideoTrimMainWindow_UI)
        self.actionSource_Files.setObjectName("actionSource_Files")
        self.actionCommmit = QtGui.QAction(VideoTrimMainWindow_UI)
        self.actionCommmit.setObjectName("actionCommmit")
        self.menuFile.addAction(self.actionSource_Files)
        self.menuFile.addAction(self.actionCommmit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(VideoTrimMainWindow_UI)
        QtCore.QMetaObject.connectSlotsByName(VideoTrimMainWindow_UI)

    def retranslateUi(self, VideoTrimMainWindow_UI):
        VideoTrimMainWindow_UI.setWindowTitle(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Video Trim", None, QtGui.QApplication.UnicodeUTF8))
        self.play_btn.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Set In", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Set Out", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Back 5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Goto In Point", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Goto Out Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Source Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "00:00:00.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "00:00:00.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "00:00:00.00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSource_Files.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Source Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommmit.setText(QtGui.QApplication.translate("VideoTrimMainWindow_UI", "Commit", None, QtGui.QApplication.UnicodeUTF8))

import qt_assets_rc
